---

# Root tasks
- hosts: localhost
  become: true
  tasks:
    - name: include settings
      include_vars:
        file: settings.yml
    - name: rpm-ostree tasks
      import_tasks: rpm-ostree.yml

# User tasks
- hosts: localhost
  become: false
  tasks:
    - name: include settings
      include_vars:
        file: settings.yml
    - name: toolbox tasks
      import_tasks: toolbox.yml
    - name: flatpak tasks
      import_tasks: flatpak.yml
    - name: miscellaneous tasks
      import_tasks: misc.yml
    - name: post install
      import_tasks: post_install.yml

- hosts: localhost
  become: false
  roles:
    - role: jaredhocutt.gnome_extensions
      vars:
        gnome_extension_ids: "{{ gnome_shell_extensions }}"
      include_vars:
        file: settings.yml