user: "janek"

rpm_ostree_update: true
rpm_ostree_install: true
rpm_ostree_packages:
  - fish
  - gnome-tweak-tool
  - libgnome-keyring
  - vim

toolbox_create: true
toolbox_update: true
toolbox_packages_install: true
toolbox_packages:
  - vim
  - fish

flatpak_packages_install: true
flatpak_packages:
  - org.gnome.Evolution
  - org.gnome.Contacts
  - org.signal.Signal
  - com.bitwarden.desktop
  - com.spotify.Client
  - io.github.celluloid_player.Celluloid
  #- org.blender.Blender
  #- org.darktable.Darktable
  #- org.gnome.Boxes
  #- org.godotengine.Godot
  #- com.visualstudio.code.oss
  #- com.valvesoftware.Steam
  #- org.nextcloud.Nextcloud
  #- org.kde.krita
  #- org.libreoffice.LibreOffice
  #- org.kde.kdenlive
  #- org.shotcut.Shotcut
flatpak_packages_remove: false
flatpak_remove:

set_gsettings: true
gnome_settings:
# `dconf watch /` to see path
  - org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
  - org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,close'
  - org.gnome.desktop.interface show-battery-percentage true

post_install_reboot: true