user: "janek"

rpm_ostree_update: true
rpm_ostree_install: true
rpm_ostree_packages:
  - fish
  - gnome-tweak-tool
  - libgnome-keyring
  - vim

toolbox_create: true
toolbox_update: true
toolbox_packages_install: true
toolbox_packages:
  - vim
  - fish

flatpak_packages_install: true
flatpak_packages:
  - org.gnome.Evolution # favorite
  - org.signal.Signal # favorite
  - com.visualstudio.code.oss # favorite
  - com.bitwarden.desktop # favorite
  - org.gnome.Contacts
  - com.spotify.Client
  - io.github.celluloid_player.Celluloid
  - org.godotengine.Godot
  - org.nextcloud.Nextcloud
  - com.valvesoftware.Steam
  #- org.blender.Blender
  #- org.darktable.Darktable
  #- org.gnome.Boxes
  #- org.kde.krita
  #- org.libreoffice.LibreOffice
  #- org.kde.kdenlive
  #- org.shotcut.Shotcut
flatpak_packages_remove: false
flatpak_remove:

set_gsettings: true
gnome_settings:
# `dconf watch /` to see path
  - org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
  - org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,close'
  - org.gnome.desktop.interface show-battery-percentage true
  - org.gnome.desktop.background picture-uri 'file:///{{ playbook_dir }}/wallpaper.jpg'
  - org.gnome.desktop.background picture-options 'zoom'
  - org.gnome.shell favorite-apps "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Evolution.desktop', 'org.signal.Signal.desktop', 'com.visualstudio.code.oss.desktop', 'com.bitwarden.desktop.desktop']"

firefox_enable: true
firefox_addons:
  - bitwarden-password-manager
  - gnome-shell-integration
fish_greeting: ""
minetime_install: true
minetime_url: "https://github.com/marcoancona/MineTime/releases/download/v1.6.4/MineTime-1.6.4.AppImage"


gnome_extension_ids:
  - 1317 # alt-tab-switcher-popup-delay-removal
  - 1509 # drop-down-terminal-x
  - 1082 # cpufreq
  - 1128 # hide-activities-button
  - 600  # launch-new-instance
  - 800  # remove-dropdown-arrows
  - 906  # sound-output-device-chooser
  - 1460 # vitals
  - 355  # status-area-horizontal-spacing

post_install_reboot: true